### ISSUE TITLE
Add enableRebound Feature

### ISSUE THREAD

**Issue by ryanlunka** [blendededge/graphql-component-oih#39]
The GraphQL component needs to be configurable to rebound on certain errors. This should mirror the functionality of the REST/HTTP component:

- When enabled, assumes a default list of reboundable HTTP response codes
- Can configure a custom list of HTTP response codes
- jsonataResponseValidator that allows you to rebound based on the response data (this one is maybe up for discussion in a GQL context)

**Comment by winklerj** [comment]
#40 #41 #42 #43 All implemented this issue
